### ISSUE TITLE
Check work for Issues 5-8

### ISSUE THREAD

**Issue by john-zoscak** [benjamin-chan/CarlsonConcertedCultivation#10]
I wrote the code for Issues 5-8 on the processData.do file and "pushed" it through I think :)

Please let me know it uploaded and whether I made any mistakes.  Also what renaming do you want me to do for Issue 4?

Thanks Ben!

**Comment by benjamin-chan** [comment]
@john-zoscak Can you add some code to generate summary statistics (mean, median, min, max) or frequency tables or histograms? Will want to check the scoring makes sense and isn't doing anything unexpected.

Assign this issue back to me when complete so I know it's ready for review.

**Comment by john-zoscak** [comment]
So I think I have everything taken care of except for the histograms.  While trying to make one for stand_gpa_09, I found some possible errors/discrepancies in the data.  For example, check observations 47 and 53.  

For 47:  self reported score 99.  max score 98
For 53:  self reported score 98.  max score 4

**Comment by benjamin-chan** [comment]
@john-zoscak Ah, yes. I missed these missing value codes for the GPA variables. Valid range should be 0.01-12.00. Can you add these?

Count | % | Value/Range | Text
-- | -- | -- | --
1,180 | 75.93 | .01 - 12.00 | Actual GPA
99 | 6.37 | 98.00 | DK
8 | .51 | 99.00 | NA; refused
267 | 17.18 | .00 | Inap.: earned a GED or did not graduate from high school (TA090590=2, 3, 8, or 9)

**Comment by benjamin-chan** [comment]
Unit test for processData.do passed
