### ISSUE TITLE
Insert call to gpaMissingValue.do in script.do

### ISSUE THREAD

**Issue by benjamin-chan** [benjamin-chan/CarlsonConcertedCultivation#12]
Insert call into proper sequence

**Comment by john-zoscak** [comment]
While looking into how to do this, I thought it may be easier to just write the code into the processData.do file so all the coding for dealing with missing values would be all together.  Would that be ok?  I will eventually figure out how to "insert call into proper sequence" and don't mind spending the time to figure that out.  Let me know which you would prefer.

I did write some new code for dealing with the GPA variables and their missing values.  See below:

/* Possible different coding scheme for GPA variables TA050584 - TA150713 */
mvdecode TA050584 TA050585 TA070559, mv(8 = .a \ 9 = .b \ 0 = .c)
mvdecode TA070559 TA070560 TA090601 TA090602 TA110682 TA110683 TA130702 ///
		 TA130703 TA150712 TA150713, mv(98 = .a \ 99 = .b \ 0 = .c)

The reason I suggest this is that the ranges of GPA scores starting at TA070560 and going to TA150713 include 8 and/or 9 as possible values for GPA.  For example TA090682 has a range of 1 - 8.6 and TA110683 1 - 10.

I think 0, 8 and 9 were the coded values for the missing values for TA050584 and TA050585.  Then in 2007 they switched to 0, 98, 99 and kept that through 2015.  However, the only "weird" thing for 2007 TA070559 there are two reported "9" values and the range of values for GPA are 1.8 - 5.5.  I interpret that as someone wasn't familiar or forgot the new coding scheme.

So the final question is whether this matters much?  Of course all variables with 0, 98, 99 need to be coded as missing, but should we worry about the occasional 9 or 8 found in those variables TA070560 and beyond?  If so, I think the coding above may correct that?

If you think that looks good, I'll put the code into the processData.do file.

Thanks Ben!

**Comment by benjamin-chan** [comment]
@john-zoscak Good catch. Looking at the codebook `data/raw/J233902/J233902_codebook.html`, they did change the missing value coding from 2005 to 2007 as you found. Go ahead and use the `mvdecode` logic you have above.

For the `script.do` part of this issue, take a look at that .do file. You'll see that it calls multiple .do files. The idea of `script.do` is that it runs everything necessary for the project. So if someone needed to recreate the whole project (data processing, cleaning, and analysis) all they would need to do is to run `script.do` instead of each .do file piecemeal. Since you had a separate .do script to recode GPAs, that needed to be inserted in the processing (between import and analysis). But now that you're going to fold the GPA recoding into `processData.do`, then this isn't necessary. So I'm closing this issue.
