### ISSUE TITLE
Score Leisure Activities

### ISSUE THREAD

**Issue by benjamin-chan** [benjamin-chan/CarlsonConcertedCultivation#8]
1. Sum Q1E4, Q1E2; for children age 6-9 years
2. Sum Q1F4, Q1F2; for children age 10+ years
3. Merge into a single leisure activity score

> ... children’s *leisure activities*, is the sum of two items (extracurricular participation and encourage hobbies) coded 1 if the target child’s mother reported participation and 0 if not.

**Comment by benjamin-chan** [comment]
First, need to recode Q1E4, Q1E2, Q1F4, Q1F2.
Raw data coding is 1 = Yes, 5 = No.
Need to recode so 1 = Yes, **0 = No**.

**Comment by benjamin-chan** [comment]
@john-zoscak We're not going to want to recode `leisure_act_total`; it's supposed to be a sum. So possible values {0, 1, 2}.

**Comment by john-zoscak** [comment]
I corrected this and #6 and did some summary statistics and frequency tables.  Also dropped leisure_act_score and fixed the sum that is just leisure_act_total.  Still need to do histograms.  However, I committed these changes and then tried to push and it said I had to pull new stuff.  I tried to pull and it said things would be overwritten.

Suggestions?

I'll need to head to class in 10 min

John
________________________________

**Comment by john-zoscak** [comment]
I corrected this and #6 and did some summary statistics and frequency tables.  Also dropped leisure_act_score and fixed the sum that is just leisure_act_total.  Still need to do histograms.  However, I committed these changes and then tried to push and it said I had to pull new stuff.  I tried to pull and it said things would be overwritten.  

Suggestions?

I'll need to head to class in 10 min

John

**Comment by john-zoscak** [comment]
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

That's the message I get when I try to pull

**Comment by benjamin-chan** [comment]
See c5d14290f7a31b47d8ef91523aee450d886b621a
